
Sys.setenv(FALK_EXTENDED_USER_RIGHTS="[{\"A\":80,\"R\":\"SC\",\"U\":105593},{\"A\":80,\"R\":\"LC\",\"U\":106896},{\"A\":81,\"R\":\"LC\",\"U\":2}]")
Sys.setenv(MYSQL_DB_LOG="db_log")
Sys.setenv(MYSQL_DB_AUTOREPORT="db_autoreport")
Sys.setenv(MYSQL_DB_DATA="NordicScirReportDataStaging")
Sys.setenv(MYSQL_HOST="db")
Sys.setenv(MYSQL_USER="root")
Sys.setenv(MYSQL_PASSWORD="root")
Sys.setenv(FALK_APP_ID="80")
Sys.setenv(FALK_USER_EMAIL="jesus@sky.no")
Sys.setenv(FALK_USER_FULLNAME="Arnie")
Sys.setenv(USERORGID="pilot")
Sys.setenv(SHINYPROXY_USERNAME="sivh")
Sys.setenv(SHINYPROXY_USERGROUPS="pilot")
Sys.setenv(R_RAP_INSTANCE="QAC")
Sys.setenv(R_RAP_CONFIG_PATH="data-raw/config")
